spring:
  application:
    name: java-api-springboot-maven
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVER_AND_PORT}/${POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8080
